# Generated by Django 3.0.8 on 2020-07-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_activelistings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelistings',
            name='image',
            field=models.ImageField(max_length=200, upload_to='image'),
        ),
    ]
