# Generated by Django 3.0.8 on 2020-07-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200723_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelistings',
            name='category',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='activelistings',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='Title Ho'),
        ),
    ]
