# Generated by Django 3.0.8 on 2020-07-23 08:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200723_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelistings',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 8, 26, 25, 91771, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activelistings',
            name='image',
            field=models.ImageField(max_length=300, upload_to='image'),
        ),
    ]
