# Generated by Django 3.0.8 on 2020-07-23 14:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200723_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelistings',
            name='current_bid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='activelistings',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 14, 8, 24, 739796, tzinfo=utc)),
        ),
    ]
