# Generated by Django 3.0.8 on 2020-07-26 03:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200724_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelistings',
            name='category',
            field=models.CharField(choices=[('FASHION', 'FASHION'), ('HOME', 'HOME'), ('ELECTRONICS', 'ELECTRONICS'), ('SPORTS', 'SPORTS'), ('H_AND_B', 'HEALTH AND BEAUTY'), ('TOYS', 'TOYS OR BABY ITEMS'), ('V_AND_M', 'VECHILE PARTS AND MOTORS'), ('OTHERS', 'OTHERS')], max_length=15),
        ),
        migrations.AlterField(
            model_name='activelistings',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 3, 35, 23, 72516, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_watchlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
