# Generated by Django 3.0.8 on 2020-07-26 03:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200726_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelistings',
            name='category',
            field=models.CharField(choices=[('FASHION', 'FASHION'), ('HOME', 'HOME'), ('ELECTRONICS', 'ELECTRONICS'), ('SPORTS', 'SPORTS'), ('HEALTH AND BEAUTY', 'HEALTH AND BEAUTY'), ('TOYS OR BABY ITEMS', 'TOYS OR BABY ITEMS'), ('VECHILE PARTS AND MOTORS', 'VECHILE PARTS AND MOTORS'), ('OTHERS', 'OTHERS')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activelistings',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 3, 44, 55, 262545, tzinfo=utc)),
        ),
    ]
