# Generated by Django 3.0.8 on 2020-07-26 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20200726_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('FASHION', 'FASHION'), ('HOME', 'HOME'), ('ELECTRONICS', 'ELECTRONICS'), ('SPORTS', 'SPORTS'), ('HEALTH AND BEAUTY', 'HEALTH AND BEAUTY'), ('TOYS OR BABY ITEMS', 'TOYS OR BABY ITEMS'), ('VEHICLE PARTS AND MOTORS', 'VEHICLE PARTS AND MOTORS'), ('OTHERS', 'OTHERS')], max_length=30),
        ),
        migrations.AlterField(
            model_name='listings',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 16, 30, 56, 76878, tzinfo=utc)),
        ),
    ]
