# Generated by Django 3.1 on 2020-08-15 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20200815_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 15, 14, 37, 14, 781684, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
